[project]
name = "TIC-TAC-GO"
version = "0.1.0"
description = ""
authors = [
    {name = "przemek890",email = "przemek.899@wp.pl"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame (>=2.6.1,<3.0.0)"
]

[tool.poetry]
package-mode = false
